import { useState } from "react";
import { jsPDF } from "jspdf";
import { FileText, Download, Loader2 } from "lucide-react";
import { DemoTag, Panel, Button, RiskBadge } from "../components/ui";
import { useActiveResult, useActiveScenario, useEnsureDemoRun } from "../hooks/useSim";
import { DAM } from "../data/demoData";
import { generateInsights } from "../engine/insights";

export default function Reports() {
  useEnsureDemoRun();
  const result = useActiveResult();
  const scenario = useActiveScenario();
  const [generating, setGenerating] = useState(false);

  const insights = result ? generateInsights(result) : [];
  const priorities = result ? [...result.impacts].sort((a, b) => b.riskScore - a.riskScore).slice(0, 8) : [];

  async function downloadPdf() {
    if (!result) return;
    setGenerating(true);
    await new Promise((r) => setTimeout(r, 300));

    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const margin = 48;
    let y = margin;
    const pageWidth = doc.internal.pageSize.getWidth();
    const lineHeight = 16;

    function heading(text: string, size = 16) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(size);
      doc.setTextColor(15, 23, 42);
      doc.text(text, margin, y);
      y += size * 1.2;
    }
    function label(text: string) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(71, 85, 105);
      doc.text(text.toUpperCase(), margin, y);
      y += 16;
    }
    function body(text: string, size = 10.5) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(size);
      doc.setTextColor(30, 41, 59);
      const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * (size + 3.5);
    }
    function row(a: string, b: string) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(51, 65, 85);
      doc.text(a, margin, y);
      doc.setFont("helvetica", "bold");
      doc.text(b, pageWidth - margin - doc.getTextWidth(b), y);
      y += lineHeight;
    }
    function ensureSpace(needed: number) {
      if (y + needed > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
    }
    function divider() {
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, y, pageWidth - margin, y);
      y += 18;
    }

    heading("AegisFlow — Dam-Break Inundation Simulation Report", 17);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated ${new Date(result.runAt).toLocaleString()} · DEMO SIMULATION DATA`, margin, y);
    y += 22;
    divider();

    label("Dam Information");
    row("Dam", `${DAM.name} (${DAM.id})`);
    row("River", DAM.river);
    row("Reservoir Capacity", `${DAM.reservoirCapacity_mcm.toLocaleString()} MCM`);
    row("Full Reservoir Level", `${DAM.fullReservoirLevel_m} m`);
    y += 8;

    label("Scenario Parameters");
    row("Scenario", scenario.name);
    row("Reservoir Level", `${scenario.reservoirLevel_m} m`);
    row("Breach Width", `${scenario.breachWidth_m} m`);
    row("Breach Depth", `${scenario.breachDepth_m} m`);
    row("Breach Formation Time", `${scenario.breachFormationTime_min} min`);
    row("Simulation Duration", `${scenario.durationMin} min`);
    row("Resolution", scenario.resolution);
    y += 8;
    divider();

    label("Simulation Results Summary");
    row("Flooded Area", `${result.summary.floodedAreaKm2.toFixed(1)} km²`);
    row("Population Exposed", result.summary.populationExposed.toLocaleString());
    row("Roads Affected", `${result.summary.roadsAffectedKm.toFixed(1)} km`);
    row("Critical Facilities Affected", String(result.summary.criticalFacilitiesAffected));
    row("Maximum Depth", `${result.summary.maxDepth.toFixed(2)} m`);
    row("Maximum Velocity", `${result.summary.maxVelocity.toFixed(2)} m/s`);
    row("Earliest Arrival", result.summary.earliestArrivalMin !== null ? `${result.summary.earliestArrivalMin} min` : "N/A");
    y += 8;
    divider();

    ensureSpace(120);
    label("Decision-Support Analysis (AI-Assisted)");
    insights.forEach((line) => {
      ensureSpace(30);
      body(`•  ${line}`);
      y += 2;
    });
    y += 8;
    divider();

    ensureSpace(140);
    label("Top Risk Priority Locations");
    priorities.forEach((p, i) => {
      ensureSpace(16);
      row(
        `${i + 1}. ${p.assetType.toUpperCase()} — ${p.assetId}`,
        `${p.riskLevel} (${p.riskScore.toFixed(0)}) · ${p.arrivalMin !== null ? Math.round(p.arrivalMin) + " min" : "N/A"}`
      );
    });
    y += 10;
    divider();

    ensureSpace(90);
    label("Methodology & Disclaimer");
    body(
      "This report is generated by a prototype hydrodynamic-approximation simulation combined with a transparent, configurable risk-scoring model. It is a decision-support artifact intended to assist emergency planning authorities and does not constitute an operational evacuation order, certified hydraulic engineering analysis, or validated emergency directive. All simulation inputs are demonstration data unless otherwise configured with real datasets. Final operational decisions remain the responsibility of designated disaster-management authorities.",
      9.5
    );

    doc.save(`AegisFlow-Report-${scenario.id}-${Date.now()}.pdf`);
    setGenerating(false);
  }

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      <header className="h-16 shrink-0 border-b border-base-700 flex items-center justify-between px-6 bg-base-900">
        <div>
          <h1 className="text-base font-bold text-white">Reports</h1>
          <p className="text-xs text-slate-500">Generate a complete simulation and impact report</p>
        </div>
        <DemoTag />
      </header>

      <div className="flex-1 overflow-y-auto p-6 grid grid-cols-3 gap-5">
        <div className="col-span-2 space-y-5">
          <Panel title="Report Preview" subtitle={scenario.name}>
            <div className="p-5 space-y-5 text-sm">
              <div>
                <div className="text-xs font-semibold text-slate-400 uppercase mb-2">Dam & Scenario</div>
                <div className="grid grid-cols-2 gap-2 text-xs text-slate-300">
                  <div>Dam: {DAM.name}</div>
                  <div>Scenario: {scenario.label}</div>
                  <div>Breach Width: {scenario.breachWidth_m} m</div>
                  <div>Duration: {scenario.durationMin} min</div>
                </div>
              </div>
              {result && (
                <div>
                  <div className="text-xs font-semibold text-slate-400 uppercase mb-2">Key Results</div>
                  <div className="grid grid-cols-3 gap-2 text-xs text-slate-300">
                    <div>Flooded Area: {result.summary.floodedAreaKm2.toFixed(1)} km²</div>
                    <div>Population: {result.summary.populationExposed.toLocaleString()}</div>
                    <div>Max Depth: {result.summary.maxDepth.toFixed(1)} m</div>
                  </div>
                </div>
              )}
              <div>
                <div className="text-xs font-semibold text-slate-400 uppercase mb-2">Decision-Support Insights</div>
                <div className="space-y-1.5">
                  {insights.slice(0, 3).map((line, i) => (
                    <div key={i} className="text-xs text-slate-400">
                      • {line}
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-400 uppercase mb-2">Top Priorities</div>
                <div className="flex flex-wrap gap-2">
                  {priorities.slice(0, 5).map((p) => (
                    <RiskBadge key={p.assetId} level={p.riskLevel} size="sm" />
                  ))}
                </div>
              </div>
            </div>
          </Panel>
        </div>

        <Panel title="Generate Report">
          <div className="p-4 space-y-3">
            <FileText size={28} className="text-accent" />
            <p className="text-xs text-slate-500 leading-relaxed">
              Includes dam information, scenario parameters, simulation summary, decision-support
              insights, risk priorities, and methodology disclaimer.
            </p>
            <Button className="w-full" onClick={downloadPdf} disabled={!result || generating}>
              {generating ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              {generating ? "Generating..." : "Download PDF Report"}
            </Button>
          </div>
        </Panel>
      </div>
    </div>
  );
}
